### ISSUE TITLE
Honor .nvmrc if it's present

### ISSUE THREAD

**Issue by StevePotter** [Almouro/bitrise-nvm-step#2]
We use the [.nvmrc file](https://github.com/creationix/nvm/blob/master/README.md#nvmrc) to store the Node version we want to install.  Have you considered checking for this and if it exists, using it instead of the `node_version` input param?  Because now I have to put the node version in two places - .nvmrc and bitrise.yaml

Thanks!

**Comment by Almouro** [comment]
Hi @StevePotter, thanks for suggesting this, it's a good idea!

I won't have time to work on this for a few days, but feel free to submit a PR of course :)

**Comment by jasonfma** [comment]
Would it be as simple as removing the required flag on the node version field? The script runs `nvm install ${node_version}` so if that field is empty would it just run `nvm install` and use the version from `.nvmrc`? If so I can submit a PR for that change.

**Comment by Almouro** [comment]
Hi @jasonfma, you're right, since [this commit](https://github.com/creationix/nvm/issues/318) it should work!

You also will have to remove the default version here: https://github.com/Almouro/bitrise-nvm-step/blob/master/step.yml#L28

Then you can test it on Bitrise by sharing it (https://github.com/Almouro/bitrise-nvm-step#share-your-own-step) and using your fork of the Bitrise step lib https://github.com/bitrise-io/bitrise-steplib

I'll have more time this weekend, if need be :)

**Comment by Almouro** [comment]
I created a PR for it.
Just need to wait for the new version to be merged in the Bitrise step lib now :)
https://github.com/bitrise-io/bitrise-steplib/pull/1277

**Comment by jasonfma** [comment]
Thanks!
